#!/usr/bin/env python3
"""Generate wiki/index.md from page frontmatter.

The index is a DERIVED catalog: every typed page's entry line is
`- [[name]] -- {description frontmatter}`. Edit a page's `description:` to
change its hook; never hand-edit index entries.

Usage:
  python3 wiki-index.py                # regenerate wiki/index.md in place
  python3 wiki-index.py --dry-run      # print what would change, write nothing
  python3 wiki-index.py --backfill     # one-time: copy existing index hooks into
                                       # page frontmatter (description; title from H1),
                                       # skipping pages that already have them
"""

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from rekall_config import VAULT, WIKI  # noqa: E402
INDEX = WIKI / "index.md"
SECTIONS = [("People", "person"), ("Projects", "project"), ("Entities", "entity"),
            ("Concepts", "concept"), ("Summaries", "summary"), ("Other pages", None)]  # None = any other `type`
PAGES = WIKI / "pages"

HEADER = """---
okf_version: "0.2"
---
# Wiki Index

Content catalog for the LLM-maintained wiki. OKF-style layout since 2026-08-22: one flat `pages/` folder; `type` in frontmatter is the taxonomy and groups this index. Browse by type through the Bases at the wiki root.

GENERATED by `rekall/scripts/wiki-index.py` from page frontmatter — do not hand-edit entries. To change a hook, edit that page's `description:` and rerun the script.
"""

FOOTER = """## Meetings

Meeting notes live in `wiki/meetings/` (one note per meeting, `type: meeting`). Browse via the meetings Base or folder — not indexed here.
"""


def frontmatter_span(text):
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 4)
    return (4, end) if end != -1 else None


def get_scalar(fm, key):
    m = re.search(rf"^{key}:[ \t]*(.+)$", fm, re.M)
    if not m:
        return None
    v = m.group(1).strip()
    if v and v[0] in "\"'" and v[-1] == v[0] and len(v) > 1:
        try:
            return json.loads(v) if v[0] == '"' else v[1:-1]
        except json.JSONDecodeError:
            return v[1:-1]
    return v or None


def pages():
    by_type = {t: s for s, t in SECTIONS if t}
    other = next(s for s, t in SECTIONS if t is None)
    for p in sorted(PAGES.glob("*.md"), key=lambda x: x.stem.lower()):
        text = p.read_text()
        span = frontmatter_span(text)
        t = get_scalar(text[span[0]:span[1]], "type") if span else None
        yield by_type.get(t, other), p


def regen(dry):
    by_section = {s: [] for s, _ in SECTIONS}
    for section, p in pages():
        text = p.read_text()
        span = frontmatter_span(text)
        desc = get_scalar(text[span[0]:span[1]], "description") if span else None
        entry = f"- [[{p.stem}]] -- {desc}" if desc else f"- [[{p.stem}]]"
        if span and get_scalar(text[span[0]:span[1]], "status") == "retired":
            entry += " (retired)"  # still listed and searchable; the pipeline no longer updates it
        by_section[section].append(entry)
    out = HEADER
    for section, _ in SECTIONS:
        if by_section[section]:
            out += f"\n## {section}\n\n" + "\n".join(by_section[section]) + "\n"
    out += "\n" + FOOTER
    old = INDEX.read_text() if INDEX.exists() else ""
    if out == old:
        print("index.md unchanged")
        return
    old_entries = len(re.findall(r"^- \[\[", old, re.M))
    new_entries = sum(len(v) for v in by_section.values())
    print(f"index.md: {old_entries} -> {new_entries} entries"
          + "".join(f", {s} {len(by_section[s])}" for s, _ in SECTIONS))
    if dry:
        print("(dry-run — not written)")
        return
    INDEX.write_text(out)
    print("written")


def backfill():
    hooks = {}
    for line in INDEX.read_text().splitlines():
        m = re.match(r"- \[\[([^\]|]+)(?:\|[^\]]*)?\]\](?: -- (.*))?$", line)
        if m:
            hooks[m.group(1).strip()] = (m.group(2) or "").strip()
    changed = 0
    for _, p in pages():
        text = p.read_text()
        span = frontmatter_span(text)
        if not span:
            print(f"  SKIP (no frontmatter): {p.relative_to(WIKI)}")
            continue
        fm = text[span[0]:span[1]]
        add = []
        if get_scalar(fm, "title") is None:
            h1 = re.search(r"^# (.+)$", text, re.M)
            title = h1.group(1).strip() if h1 else p.stem.replace("-", " ").title()
            add.append(f"title: {json.dumps(title)}")
        if get_scalar(fm, "description") is None:
            desc = hooks.get(p.stem)
            if not desc:
                m = re.search(r"\*\*Summary\*\*:\s*(.+)", text)
                # ponytail: first sentence of Summary as fallback; good enough for stragglers
                desc = re.split(r"(?<=[.!?]) ", m.group(1).strip())[0] if m else ""
            if desc:
                add.append(f"description: {json.dumps(desc)}")
        if add:
            new_fm = fm.rstrip("\n") + "\n" + "\n".join(add) + "\n"
            p.write_text(text[:span[0]] + new_fm + text[span[1]:])
            changed += 1
    print(f"backfilled frontmatter on {changed} pages")


if __name__ == "__main__":
    if "--backfill" in sys.argv:
        backfill()
    else:
        regen("--dry-run" in sys.argv)
